build/pupmod-nfs.spec
manifests/client.pp
spec/classes/client_spec.rb

* The exec that enabled the nfs kernel module was not guaranteed to fire
off *after* the proper settings had been made to the
nfs_callback_tcpport option in modprobe.d.
* Simplified the detection of the NFS kernel module being loaded for
firing off the modprobe exec.
SIMP-549 #close

(SIMP-549) Fix modprobe ordering for nfs_callback

---

build/pupmod-nfs.spec
manifests/init.pp
manifests/lvm2.pp
spec/classes/init_spec.rb

Found a bug in the nfs-utils rpm which will not allow upgrades
unless the lvm2 package is the latest.  Created a one-off class
to manage the package which can be deleted once the bug is fixed
upstream.
SIMP-926 #close lvm2 latest
Change-Id: I9f142b36762eba5d95bdb69718d2af5a4f454ac7

(SIMP-926) Ensure the lvm2 package is latest

---

manifests/client.pp
manifests/server.pp

change permissions from 640 to 644 on /etc/exports.  644
still meets security requirements.  Vagrant dies if it can't read the
/etc/exports file.
SIMP-1525 #close

(SIMP-1525) Change permission on /etc/exports

---

.fixtures.yml
CHANGELOG
build/rpm_metadata/requires
manifests/client.pp
manifests/init.pp
manifests/server.pp
metadata.json
spec/classes/client_spec.rb
spec/classes/init_spec.rb

Replaced sysctl::value with augeas 'sysctl' native type.
SIMP-1684 #comment done in nfs
SIMP-2242 #close

(SIMP-1684) Remove pupmod-simp-sysctl

---

manifests/idmapd.pp

- put logic for checking service in () to make sure it executed correctly
- changed the path for CentOS server to /sbin/service
SIMP-2663 #comment  updated the same thing in nfs module

(SIMP-2663) Fix path for service and selection logic

---

manifests/client/mount.pp
manifests/idmapd.pp
manifests/init.pp
manifests/server/export.pp
manifests/service_names.pp
spec/defines/client/mount_spec.rb

When using autofs, and particularly, the wildcard mounts, the naming
conventions used in client::mount were incorrect.
SIMP-2285 #comment Fix client::mount resource naming

(SIMP-2285) Fix naming when using autofs

---

CHANGELOG
build/rpm_metadata/requires
metadata.json

The simp-tcpwrappers version in the metadata.json was incorrect. The
RPM dependencies were fine.
SIMP-2777 #close

(SIMP-2777) Fix metadata.json versions

---

CHANGELOG
metadata.json

Last released version is 6.0.2, so all subsequent changes are for 6.0.3.

(SIMP-3372) nfs - version/changelog cleanup as prep for tagging

---

CHANGELOG
build/rpm_metadata/requires
metadata.json

concat 3.0.0 is fully backward compatible with 2.x.

(SIMP-3613) nfs: Update to concat 3.0.0

---

.fixtures.yml

Pin concat to 3.0.0 in .fixtures.yml, as metadata.json bounds
concat to < 4.0.0.

(SIMP-3613) nfs: Pin concat to 3.0.0 in .fixtures.yml

---

.fixtures.yml
.gitlab-ci.yml
.travis.yml
CHANGELOG
manifests/client/mount.pp
manifests/client/mount/connection.pp
manifests/client/stunnel.pp
manifests/client/stunnel/v4.pp
manifests/init.pp
manifests/install.pp
manifests/server/stunnel.pp
manifests/service_names.pp
metadata.json
spec/acceptance/nodesets/default.yml
spec/acceptance/suites/default/00_basic_test_spec.rb
spec/acceptance/suites/default/02_krb5_test_spec.rb
spec/acceptance/suites/stunnel/00_basic_test_spec.rb
spec/acceptance/suites/stunnel/03_stunnel_test_spec.rb
spec/classes/client/stunnel_spec.rb
spec/classes/client_spec.rb
spec/classes/idmapd_spec.rb
spec/classes/init_spec.rb
spec/classes/server/stunnel_spec.rb
spec/classes/server_spec.rb

On systemd systems, the stunnel service is now a dependency of the NFS
servers and mounts managed by this module.
SIMP-4637 #close

(SIMP-4637) Use stunnel systemd service deps

---

.fixtures.yml
CHANGELOG
manifests/client/mount.pp
metadata.json
spec/acceptance/suites/default/00_basic_test_spec.rb
spec/acceptance/suites/default/10_krb5_test_spec.rb

* Allow users to set the 'ensure' state of their client mountpoints in
case they don't want them to be mounted by default.
* Fix the acceptance and spec tests
SIMP-5008 #close

(SIMP-5008) Added nfs::client::mount::ensure param

---

.gitlab-ci.yml

Explicitly set suite so each job is clearly defined and there
are no overlaps with implied suites.  Without this change,
the stunnel suite is unnecessarily executed multiple times
for the same configuration.
SIMP-7018 #close

(SIMP-7018) simp-nfs runs same tests multiple times in GitLab

---

spec/defines/server/export_spec.rb
templates/etc/export.erb

An issue was discovered while testing simp_nfs with EL8 where the
/etc/exports was not adding `::1` to entries on IPv6 systems and this
was causing connections over `stunnel` to occasionally fail.
This patch ensures that IPv6 and IPv4 entries are added if the system is
IPv6 enabled.
SIMP-7453 #comment Fix ::1 issue in /etc/exports

(SIMP-7453) Fix NFS export code

---

.gitlab-ci.yml
.travis.yml
Gemfile

This patch updates the puppet and ruby versions in the Gitlab CI
pipeline to reflect the latest PE LTS releases.  Most notably, it adds
specific tests for PE2019.8 LTS.
SIMP-7892 #close
[SIMP-7848] #comment Add PE2019.8 to GL CI in pupmod-simp-nfs
[SIMP-7855] #comment Update GL CI to PE2018.1.15 in pupmod-simp-nfs
[SIMP-7848]: https://simp-project.atlassian.net/browse/SIMP-7848
[SIMP-7855]: https://simp-project.atlassian.net/browse/SIMP-7855

(SIMP-7848) Add PE2019.8 to pupmod-simp-nfs GL pipeline

---

.github/workflows/pr_glci.yml
.github/workflows/pr_glci_manual.yml
.github/workflows/pr_tests.yml
.gitlab-ci.yml

This patch updates the standardized GitHub Actions that trigger GLCI
pipelines:
- Still preemptively cancels existing GLCI pipelines for the same
branch, EXCEPT when a pipeline is for the same commit hashref.
- Refactored common GLCI logic into new composite run steps actions:
- [github-action-gitlab-ci-pipeline-trigger@v1][0]
- [github-action-gitlab-ci-syntax-check@v1][1]
This patch also enforces the standardized asset baseline using
simp/puppetsync, and may apply other updates to ensure conformity.
CI: SKIP MATRIX
[SIMP-9316] #close
[SIMP-9266] #comment Standardized GHA + assets in pupmod-simp-nfs
[SIMP-9279] #comment `.fixtures.yml` triggers GLCI acc for pupmod-simp-nfs
[0]: https://github.com/simp/github-action-gitlab-ci-pipeline-trigger
[1]: …

(SIMP-9266) Improve GHA GCLI trigger in pupmod-simp-nfs

---

.fixtures.yml
.gitlab-ci.yml
CHANGELOG
Gemfile
manifests/client/mount.pp
spec/acceptance/nodesets/default.yml
spec/classes/base/config_spec.rb
spec/classes/base/service_spec.rb
spec/classes/client/config_spec.rb
spec/classes/client/service_spec.rb
spec/classes/client/tcpwrappers_spec.rb
spec/classes/client_spec.rb
spec/classes/idmapd/server_spec.rb
spec/classes/init_spec.rb
spec/classes/install_spec.rb
spec/classes/server/config_spec.rb
spec/classes/server/firewall/nfsv3and4_spec.rb
spec/classes/server/firewall/nfsv4_spec.rb
spec/classes/server/firewall_spec.rb
spec/classes/server/service_spec.rb
spec/classes/server/stunnel_spec.rb
spec/classes/server/tcpwrappers_spec.rb
spec/classes/server_spec.rb
spec/defines/client/mount/connection_spec.rb
spec/defines/client/mount_spec.rb
spec/defines/client/stunnel_spec.rb
spec/defines/server/export_spec.rb
spec/spec_helper_acceptance.rb

* Add a Puppet 7 acceptance test
* Remove check for Puppet >=6 in .fixtures.yml
* Fail acceptance tests if no examples are executed.
[SIMP-9666] #comment pupmod-simp-nfs acceptance tests configured
SIMP-10049 #close
[SIMP-9666]: https://simp-project.atlassian.net/browse/SIMP-9666

(SIMP-10049) nfs Add Puppet 7 acceptance test

---

spec/acceptance/nodesets/default.yml
spec/acceptance/nodesets/oel.yml

Maintenance:
- Add ssh keepalive configuration to the nodesets
- Remove unnecessary EPEL yum repo configuration in nodesets.
- EPEL repos are automatically installed by simp-beaker-helpers
during node configuration.
[SIMP-10385] #close
[SIMP-10385]: https://simp-project.atlassian.net/browse/SIMP-10385

(SIMP-10385) ssh acceptance tests random SUT ssh failures

---

.fixtures.yml
.gitignore
.gitlab-ci.yml
CHANGELOG
metadata.json
spec/acceptance/nodesets/default.yml
spec/acceptance/nodesets/oel.yml

This patch updates from camptocamp/systemd 2.x to puppet/systemd 3.x
This bump is driven by simp/simp-core#829

Update deps to use puppet/systemd

---

CHANGELOG
manifests/base/service.pp
metadata.json
spec/classes/base/service_spec.rb

Fix unmask_rpc-gssd.service exec resource
